frontend/frontend/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf.urls import url
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('', include('sedes.urls')),
    path('admin/', admin.site.urls),
    url('accounts/login/', auth_views.LoginView.as_view(redirect_authenticated_user=True), name='login'),
    url('accounts/logout/', auth_views.LogoutView.as_view(), name='logout'),
]

frontend/sedes/urls.py
from django.urls import path

from . import views

urlpatterns = [
    #usuarios
    path('', views.UsuarioDetail.as_view(template_name= 'usuarios/usuario_detail.html'), name= 'profile'),
    path('usuario/modificar', views.UsuarioUpdate.as_view(template_name= 'usuarios/usuario_form.html'), name= 'modificar_usuario'),
    path('usuario/<int:pk>', views.UsuarioDetail.as_view(template_name= 'usuarios/usuario_detail.html'), name= 'ver_usuario'),
    path('usuario/crear', views.UsuarioCreate.as_view(template_name= 'usuarios/registro.html'), name= 'crear_usuario'),
    
    #sedes
    path('sedes', views.SedeList.as_view(), name='lista_sedes'),
    path('sedes/ver/<int:pk>', views.SedeDetail.as_view(), name='detalle_sede'),
    path('sedes/crear', views.SedeCreate.as_view(), name='crear_sede'),
    path('sedes/modificar/<int:pk>', views.SedeUpdate.as_view(), name='modificar_sede'),
    path('sedes/eliminar/<int:pk>', views.SedeDelete.as_view(), name='eliminar_sede'),

    #productos
    path('productos', views.ProductoList.as_view(), name='lista_productos'),
    path('productos/ver/<int:pk>', views.ProductoDetail.as_view(), name='detalle_producto'),
    path('productos/crear', views.ProductoCreate.as_view(), name='crear_producto'),
    path('productos/modificar/<int:pk>', views.ProductoUpdate.as_view(), name='modificar_producto'),
    path('productos/eliminar/<int:pk>', views.ProductoDelete.as_view(), name='eliminar_producto'),

    #bodegas
    path('bodegas', views.BodegaList.as_view(), name='lista_bodegas'),
    path('bodegas/ver/<int:pk>', views.BodegaDetail.as_view(), name='detalle_bodega'),
    path('bodegas/crear', views.BodegaCreate.as_view(), name='crear_bodega'),
    path('bodegas/modificar/<int:pk>', views.BodegaUpdate.as_view(), name='modificar_bodega'),
    path('bodegas/eliminar/<int:pk>', views.BodegaDelete.as_view(), name='eliminar_bodega'),

    #categorias
    path('categorias', views.CategoriaList.as_view(), name='lista_categorias'),
    path('categorias/ver/<int:pk>', views.CategoriaDetail.as_view(), name='detalle_categoria'),
    path('categorias/crear', views.CategoriaCreate.as_view(), name='crear_categoria'),
    path('categorias/modificar/<int:pk>', views.CategoriaUpdate.as_view(), name='modificar_categoria'),
    path('categorias/eliminar/<int:pk>', views.CategoriaDelete.as_view(), name='eliminar_categoria'),

    #clientes
    path('clientes', views.ClienteList.as_view(), name='lista_clientes'),
    path('cliente/crear', views.ClienteCreate.as_view(), name='crear_cliente'),
    path('cliente/modificar/<int:pk>', views.ClienteUpdate.as_view(), name='modificar_cliente'),
    path('cliente/eliminar/<int:pk>', views.ClienteDelete.as_view(), name='eliminar_cliente'),

    #ventas
    path('ventas', views.VentasList.as_view(), name='lista_ventas'),
    path('venta/crear', views.VentaCreate, name='crear_venta'),
    path('venta/crearpdf/<int:pk>', views.PDFVentaDetail.as_view(), name='pdf_venta'),
    path('venta/ver/<int:pk>', views.VentaDetail.as_view(), name='detalle_venta'),
    path('venta/reportes', views.reporte_ventas, name="reporte_ventas"),
    
    #inventario
    path('inventario/<int:pk>', views.InventarioUpdate.as_view(), name='modificar_inventario'),
]

frontend/sedes/models.py
from django.db import models
from django.contrib.auth.models import AbstractBaseUser
from django.contrib.auth.models import PermissionsMixin
from django.utils.translation import gettext_lazy as _
from django.utils import timezone
from django.core.validators import MaxValueValidator, MinValueValidator
from django.conf import settings

from .managers import CustomUserManager
from .custom_fields import NameField

# Usuario del sistema, este se utiliza para la autenticacion y permisos
# ademas de poder acceder al sistema con el
# para crear el primer usuario se puede usar el comando en el directorio donde se encuentra el modelo
# $ python manage.py createsuperuser
# y seguir las instrucciones que presenta este script en la consola de comandos
class Usuario(AbstractBaseUser, PermissionsMixin):
    dpi = models.BigIntegerField(
        unique=True,
        validators=[
            MaxValueValidator(9999999999999),

            MinValueValidator(100000000000)
        ]
    )

    nombre = models.CharField(max_length=300)
    fecha_nacimiento = models.DateField('Fecha Nacimiento')
    email = models.EmailField(_('Correo Electronico'), primary_key=True)

    is_admin = models.BooleanField(default=False)
    is_staff = models.BooleanField(default=False)
    is_active = models.BooleanField(default=True)

    date_joined = models.DateTimeField(default=timezone.now)

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['dpi', 'fecha_nacimiento']

    objects = CustomUserManager()

    def __str__(self):
        return "%s (%s)" % (self.dpi, self.email)

    # Permisos asociados a un usuario
    # sirve para realizar toda la gestion de control de ORM
    class Meta:
        permissions = (("registrar_cliente", "Para registrar clientes de una sede"),
                   ("registrar_venta", "Para registrar ventas de productos"),
                   ("visualizar_reporte", "Para visualizar reportes de ventas"),
                   ("actualizar_inventario", "Para modificar la cantidad de productos del inventario"),
                   ("solicitar_transferencia", "Para solicitar una transferencia de productos"),
                   ("ordenes_transferencia_externa", "Para revisar ordenes de transferencias entre sedes"),
                   ("ordenes_transferencia_interna", "Para revisar ordenes de transferencias entre bodegas"),
                   ("ordenes_venta", "Para modificar el estado de entregado de una orden de venta"),
                   ("ordenes_transferencia", "Para modificar el estado de entregado de una orden de transferencia"))

# Sedes que contienen bodegas este es el modelo principal de la app
class Sede(models.Model):
    alias = models.CharField(max_length=200, unique= True)
    direccion = models.CharField(max_length=500)
    departamento = models.CharField(max_length=50)
    municipio = models.CharField(max_length=50)
    encargado = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    numero_bodegas = models.IntegerField(default=0)

    def __str__(self):
        return "%s [%s]" % (self.alias, self.encargado)


# Este modelo presenta una bodega perteneciente a una sede
# en esta se pueden encontrar productos relacionados a ella
class Bodega(models.Model):
    nombre = models.CharField(max_length=50)
    direccion = models.CharField(max_length=500)
    activada = models.BooleanField(default= True)
    encargado = models.ForeignKey('Usuario', on_delete=models.CASCADE)
    productos = models.ManyToManyField('Producto', through='BodegaProducto')

    def __str__(self):
        return self.nombre

class BodegaProducto(models.Model):
    bodega = models.ForeignKey('Bodega', on_delete= models.CASCADE)
    producto = models.ForeignKey('Producto', on_delete= models.CASCADE)
    cantidad = models.IntegerField(verbose_name='Cantidad de productos en existencia', default= 0, 
        validators=[
            MinValueValidator(0)
        ])

    def __str__(self):
        return "%s unidades de %s en %s" % (self.cantidad, self.producto, self.bodega)
# Este modelo indica un producto dentro de una bodega
# es una especie de control de inventario
class Producto(models.Model):
    sku = models.CharField('SKU', max_length=50, unique=True)
    codigo_barras = models.CharField('Codigo de Barras', max_length=50)
    nombre = models.CharField(max_length=50)
    descripcion = models.CharField(max_length=500)
    precio = models.DecimalField(max_digits=12, decimal_places=2)
    categorias = models.ManyToManyField('Categoria')
    

    def __str__(self):
        return "%s [ %s ]" % (self.nombre, self.sku) 

# Categoria de un producto
# este tiene una relacion de muchos a muchos asimetrica con el modelo Producto
class Categoria(models.Model):
    nombre = NameField('Nombre de categoria', unique=True, max_length=25)

    def __str__(self):
        return "Categoria %s" % self.nombre

# Venta de un producto, realizada por un usuario vendedor
class Venta(models.Model):
    cliente = models.ForeignKey('Cliente', on_delete=models.CASCADE)
    vendedor = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='vendedor')

    fecha_facturacion = models.DateField('Fecha de facturacion')

    DOMICILIO = 'D'
    LOCAL = 'L'
    VENTA_ESTADO_CHOICES = [
        (DOMICILIO, 'A domicilio'),
        (LOCAL, 'Local')
    ]

    tipo = models.CharField(
        max_length=1, choices=VENTA_ESTADO_CHOICES, default=LOCAL)
    repartidor = models.ForeignKey(
        settings.AUTH_USER_MODEL, null=True, on_delete=models.SET_NULL, related_name='repartidor', blank= True)

    fecha_entrega = models.DateField('Fecha de entrega', auto_now=True)
    entregada = models.BooleanField(default=False)

    productos = models.ManyToManyField('Producto', through= 'ProductoVenta', blank= True)

# En este se asocia un producto con una venta
# sirve para tomar en cuenta cuanto producto descontar del inventario
# y calcular el total de la factura
class ProductoVenta(models.Model):
    producto = models.ForeignKey('Producto', on_delete=models.CASCADE)
    venta = models.ForeignKey('Venta', null=True, on_delete=models.SET_NULL)
    cantidad = models.DecimalField('Cantidad', decimal_places=2, max_digits=12, validators= [MinValueValidator(0)])

# Cliente de una venta
class Cliente(models.Model):
    dpi = models.BigIntegerField(
        unique=True,
        validators=[
            MaxValueValidator(9999999999999),

            MinValueValidator(100000000000)
        ],
        primary_key= True
    )
    nombre = models.CharField(max_length=200)
    nit = models.CharField(max_length=15)
    direccion = models.CharField(max_length=500)
    sedes = models.ManyToManyField('Sede', verbose_name='Sedes a las que pertenece el cliente')

    def __str__(self):
        return "%s [ %s ]" % (self.nombre, self.dpi)

# Factura de una venta, contiene el total de la venta junto si esta fue
# a domicilio se recarga 10% del subtotal
class Factura(models.Model):
    venta = models.ForeignKey('Venta', on_delete=models.SET_NULL, null=True)
    subtotal = models.DecimalField(decimal_places=2, max_digits=12)
    recargo = models.DecimalField(decimal_places=2, max_digits=5)
    total = models.DecimalField(decimal_places=2, max_digits=12)

# Estos logs sirven para revisar la actualizacion del inventario por parte
# del usuario encargado de sede
class LogActualizacionInventario(models.Model):
    producto = models.ForeignKey(
        'Producto', on_delete=models.SET_NULL, null=True)
    cantidad_nueva = models.IntegerField()
    cantidad_vieja = models.IntegerField()
    descripcion = models.CharField(max_length=500)
    usuario = models.ForeignKey(
        settings.AUTH_USER_MODEL, on_delete=models.SET_NULL, null=True)
    fecha = models.DateField('Fecha de cambio', auto_now_add=True)

frontend/sedes/templates/bodegas/bodegas_confirm_delete.html
<!-- Esta vista muestra una confirmacion si se desea eliminar una bodega -->

{% extends '../base.html' %}
{% block body_block %}

<h1>Eliminar &quot;{{ object.nombre }}&quot;</h1>
<form method="post">
    {% csrf_token %}
    <p>
        <strong>¿Estas seguro que deseas eliminar esta bodega?</strong>
    </p>
    <br>
    <input class="btn btn-danger" type="submit" value="Confirmar" />
</form>

{% endblock %}

frontend/sedes/templates/bodegas/bodegas_detail.html
<!-- Esta vista muestra el detalle de una bodega -->

{% extends '../base.html' %}
{% block body_block %}

<h1>{{ object.nombre }}</h1>

<p>Direccion: {{object.direccion}}</p>
<p>Estado: <td>{% if object.activada %}{{ "Activa" }}{% else %}{{ "Inactiva" }}{% endif %}</td></p>
<p>Encargado: <a href='{% url "ver_usuario" object.encargado.dpi %}'>{{ object.encargado.email }}</a></p>

<!-- Por hacer: detalle de encargado y de bodegas -->

<h3>Productos en la bodega</h3>

<table class="table table-striped table-hover thead-dark table-dark">
    <thead class="">
        <tr>
            <th>SKU</th>
            <th>Codigo de Barras</th>
            <th>Nombre</th>
            <th>Descripcion</th>
            <th>Precio</th>
            <th>Categorias</th>
            <th>Cantidad disponible</th>
        </tr>
    </thead>
    <tbody>
        {% for bp in object.bodegaproducto_set.all %}
        <tr {% if bp.cantidad == 0 %} class="danger"{%endif%}>
            <td><a href="{% url "detalle_producto"  bp.producto.id  %}">{{ bp.producto.sku }}</a></td>
            <td>{{ bp.producto.codigo_barras }}</td>
            <td>{{ bp.producto.nombre }}</td>
            <td>{{ bp.producto.descripcion }}</td>
            <td>{{ bp.producto.precio }}</a></td>
            <td> 
                <ul>
                {% for categoria in bp.producto.categorias.all %}
                    <li>{{ categoria.nombre }} </li>
                {% endfor %} 
                </ul>
            </td>
            <td>
                {% if bp.cantidad == 0%} <span class="text-danger">{{bp.cantidad}} unidades</span>{% else %}<span class="text-success">{{ bp.cantidad }}</span> unidades {% endif %}
            </td>
            <td>
                <a href="{% url "modificar_inventario"  bp.id  %}" class="btn btn-xs btn-warning"> <span class="glyphicon glyphicon-plus"></span> Modificar inventario</a>
            </td>
        </tr>

        {% endfor %}
    </tbody>
</table>
<a href="{% url "modificar_bodega"  object.id  %}" class="btn btn-success"> <span class="glyphicon glyphicon-pencil"></span> Modificar</a>
                

{% endblock %}

frontend/sedes/templates/bodegas/bodegas_form.html
<!-- Esta vista muestra todas las bodegas que hay disponibles -->

{% extends '../base.html' %}
{% block body_block %}

{% if object.nombre %}
<h1>Modificar &quot;{{ object.nombre }}&quot;</h1>
{% else %}

<h1>Crear una bodega</h1>
{% endif %}
<form  method="post" class="form">
{% csrf_token %}
{{ form.as_p }}
<input class="btn btn-success" type="submit"  value="Crear bodega"  />
</form>

{% endblock %}

frontend/sedes/templates/bodegas/bodegas_list.html
<!-- Esta vista muestra todas las bodegas que hay disponibles -->

{% extends '../base.html' %}
{% block body_block %}

<h1>Bodegas</h1>

<a class="btn btn-success" href="{% url "crear_bodega" %}">Crear bodega</a>

<table class="table table-striped">
    <thead class="thead-dark">
        <tr>
            <th>Nombre</th>
            <th>Direccion</th>
            <th>Estado</th>
            <th>Encargado</th>
            <th colspan="3">Acciones</th>
        </tr>
    </thead>
    <tbody class="table-hover">
        {% for bodega in object_list %}
        <tr>
            <td><a href="{% url "detalle_bodega"  bodega.id  %}">{{ bodega.nombre }}</a></td>
            <td>{{ bodega.direccion }}</td>
            <td>{% if bodega.activada %}{{ "Activa" }}{% else %}{{ "Inactiva" }}{% endif %}</td>
            <td><a href='{% url "ver_usuario" bodega.encargado.dpi %}'>{{ bodega.encargado.email }}</a></td>    
            <td>
                <a href="{% url "modificar_bodega"  bodega.id  %}"> <span class="glyphicon glyphicon-pencil">&nbsp;</span></a>
                <a href="{% url "eliminar_bodega"  bodega.id  %}"> <span class="glyphicon glyphicon-remove">&nbsp;</span></a>
            </td>
        </tr>

        {% endfor %}
    </tbody>
</table>

{% endblock %}