frontend/frontend/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf.urls import url
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('', include('sedes.urls')),
    path('admin/', admin.site.urls),
    url('accounts/login/', auth_views.LoginView.as_view(redirect_authenticated_user=True), name='login'),
    url('accounts/logout/', auth_views.LogoutView.as_view(), name='logout'),
]

frontend/sedes/urls.py
from django.urls import path

from . import views

urlpatterns = [
    #usuarios
    path('', views.UsuarioDetail.as_view(template_name= 'usuarios/usuario_detail.html'), name= 'profile'),
    path('usuario/modificar', views.UsuarioUpdate.as_view(template_name= 'usuarios/usuario_form.html'), name= 'modificar_usuario'),
    path('usuario/<int:pk>', views.UsuarioDetail.as_view(template_name= 'usuarios/usuario_detail.html'), name= 'ver_usuario'),
    path('usuario/crear', views.UsuarioCreate.as_view(template_name= 'usuarios/registro.html'), name= 'crear_usuario'),
    
    #sedes
    path('sedes', views.SedeList.as_view(), name='lista_sedes'),
    path('sedes/ver/<int:pk>', views.SedeDetail.as_view(), name='detalle_sede'),
    path('sedes/crear', views.SedeCreate.as_view(), name='crear_sede'),
    path('sedes/modificar/<int:pk>', views.SedeUpdate.as_view(), name='modificar_sede'),
    path('sedes/eliminar/<int:pk>', views.SedeDelete.as_view(), name='eliminar_sede'),

    #productos
    path('productos', views.ProductoList.as_view(), name='lista_productos'),
    path('productos/ver/<int:pk>', views.ProductoDetail.as_view(), name='detalle_producto'),
    path('productos/crear', views.ProductoCreate.as_view(), name='crear_producto'),
    path('productos/modificar/<int:pk>', views.ProductoUpdate.as_view(), name='modificar_producto'),
    path('productos/eliminar/<int:pk>', views.ProductoDelete.as_view(), name='eliminar_producto'),

    #bodegas
    path('bodegas', views.BodegaList.as_view(), name='lista_bodegas'),
    path('bodegas/ver/<int:pk>', views.BodegaDetail.as_view(), name='detalle_bodega'),
    path('bodegas/crear', views.BodegaCreate.as_view(), name='crear_bodega'),
    path('bodegas/modificar/<int:pk>', views.BodegaUpdate.as_view(), name='modificar_bodega'),
    path('bodegas/eliminar/<int:pk>', views.BodegaDelete.as_view(), name='eliminar_bodega'),

    #categorias
    path('categorias', views.CategoriaList.as_view(), name='lista_categorias'),
    path('categorias/ver/<int:pk>', views.CategoriaDetail.as_view(), name='detalle_categoria'),
    path('categorias/crear', views.CategoriaCreate.as_view(), name='crear_categoria'),
    path('categorias/modificar/<int:pk>', views.CategoriaUpdate.as_view(), name='modificar_categoria'),
    path('categorias/eliminar/<int:pk>', views.CategoriaDelete.as_view(), name='eliminar_categoria'),

    #clientes
    path('clientes', views.ClienteList.as_view(), name='lista_clientes'),
    path('cliente/crear', views.ClienteCreate.as_view(), name='crear_cliente'),
    path('cliente/modificar/<int:pk>', views.ClienteUpdate.as_view(), name='modificar_cliente'),
    path('cliente/eliminar/<int:pk>', views.ClienteDelete.as_view(), name='eliminar_cliente'),

    #ventas
    path('ventas', views.VentasList.as_view(), name='lista_ventas'),
    path('venta/crear', views.VentaCreate, name='crear_venta'),
    path('venta/crearpdf/<int:pk>', views.PDFVentaDetail.as_view(), name='pdf_venta'),
    path('venta/ver/<int:pk>', views.VentaDetail.as_view(), name='detalle_venta'),
    path('venta/reportes', views.reporte_ventas, name="reporte_ventas"),
    
    #inventario
    path('inventario/<int:pk>', views.InventarioUpdate.as_view(), name='modificar_inventario'),
]

frontend/sedes/models.py
from django.db import models
from django.contrib.auth.models import AbstractBaseUser
from django.contrib.auth.models import PermissionsMixin
from django.utils.translation import gettext_lazy as _
from django.utils import timezone
from django.core.validators import MaxValueValidator, MinValueValidator
from django.conf import settings

from .managers import CustomUserManager
from .custom_fields import NameField

# Usuario del sistema, este se utiliza para la autenticacion y permisos
# ademas de poder acceder al sistema con el
# para crear el primer usuario se puede usar el comando en el directorio donde se encuentra el modelo
# $ python manage.py createsuperuser
# y seguir las instrucciones que presenta este script en la consola de comandos
class Usuario(AbstractBaseUser, PermissionsMixin):
    dpi = models.BigIntegerField(
        unique=True,
        validators=[
            MaxValueValidator(9999999999999),

            MinValueValidator(100000000000)
        ]
    )

    nombre = models.CharField(max_length=300)
    fecha_nacimiento = models.DateField('Fecha Nacimiento')
    email = models.EmailField(_('Correo Electronico'), primary_key=True)

    is_admin = models.BooleanField(default=False)
    is_staff = models.BooleanField(default=False)
    is_active = models.BooleanField(default=True)

    date_joined = models.DateTimeField(default=timezone.now)

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['dpi', 'fecha_nacimiento']

    objects = CustomUserManager()

    def __str__(self):
        return "%s (%s)" % (self.dpi, self.email)

    # Permisos asociados a un usuario
    # sirve para realizar toda la gestion de control de ORM
    class Meta:
        permissions = (("registrar_cliente", "Para registrar clientes de una sede"),
                   ("registrar_venta", "Para registrar ventas de productos"),
                   ("visualizar_reporte", "Para visualizar reportes de ventas"),
                   ("actualizar_inventario", "Para modificar la cantidad de productos del inventario"),
                   ("solicitar_transferencia", "Para solicitar una transferencia de productos"),
                   ("ordenes_transferencia_externa", "Para revisar ordenes de transferencias entre sedes"),
                   ("ordenes_transferencia_interna", "Para revisar ordenes de transferencias entre bodegas"),
                   ("ordenes_venta", "Para modificar el estado de entregado de una orden de venta"),
                   ("ordenes_transferencia", "Para modificar el estado de entregado de una orden de transferencia"))

# Sedes que contienen bodegas este es el modelo principal de la app
class Sede(models.Model):
    alias = models.CharField(max_length=200, unique= True)
    direccion = models.CharField(max_length=500)
    departamento = models.CharField(max_length=50)
    municipio = models.CharField(max_length=50)
    encargado = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    numero_bodegas = models.IntegerField(default=0)

    def __str__(self):
        return "%s [%s]" % (self.alias, self.encargado)


# Este modelo presenta una bodega perteneciente a una sede
# en esta se pueden encontrar productos relacionados a ella
class Bodega(models.Model):
    nombre = models.CharField(max_length=50)
    direccion = models.CharField(max_length=500)
    activada = models.BooleanField(default= True)
    encargado = models.ForeignKey('Usuario', on_delete=models.CASCADE)
    productos = models.ManyToManyField('Producto', through='BodegaProducto')

    def __str__(self):
        return self.nombre

class BodegaProducto(models.Model):
    bodega = models.ForeignKey('Bodega', on_delete= models.CASCADE)
    producto = models.ForeignKey('Producto', on_delete= models.CASCADE)
    cantidad = models.IntegerField(verbose_name='Cantidad de productos en existencia', default= 0, 
        validators=[
            MinValueValidator(0)
        ])

    def __str__(self):
        return "%s unidades de %s en %s" % (self.cantidad, self.producto, self.bodega)
# Este modelo indica un producto dentro de una bodega
# es una especie de control de inventario
class Producto(models.Model):
    sku = models.CharField('SKU', max_length=50, unique=True)
    codigo_barras = models.CharField('Codigo de Barras', max_length=50)
    nombre = models.CharField(max_length=50)
    descripcion = models.CharField(max_length=500)
    precio = models.DecimalField(max_digits=12, decimal_places=2)
    categorias = models.ManyToManyField('Categoria')
    

    def __str__(self):
        return "%s [ %s ]" % (self.nombre, self.sku) 

# Categoria de un producto
# este tiene una relacion de muchos a muchos asimetrica con el modelo Producto
class Categoria(models.Model):
    nombre = NameField('Nombre de categoria', unique=True, max_length=25)

    def __str__(self):
        return "Categoria %s" % self.nombre

# Venta de un producto, realizada por un usuario vendedor
class Venta(models.Model):
    cliente = models.ForeignKey('Cliente', on_delete=models.CASCADE)
    vendedor = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='vendedor')

    fecha_facturacion = models.DateField('Fecha de facturacion')

    DOMICILIO = 'D'
    LOCAL = 'L'
    VENTA_ESTADO_CHOICES = [
        (DOMICILIO, 'A domicilio'),
        (LOCAL, 'Local')
    ]

    tipo = models.CharField(
        max_length=1, choices=VENTA_ESTADO_CHOICES, default=LOCAL)
    repartidor = models.ForeignKey(
        settings.AUTH_USER_MODEL, null=True, on_delete=models.SET_NULL, related_name='repartidor', blank= True)

    fecha_entrega = models.DateField('Fecha de entrega', auto_now=True)
    entregada = models.BooleanField(default=False)

    productos = models.ManyToManyField('Producto', through= 'ProductoVenta', blank= True)

# En este se asocia un producto con una venta
# sirve para tomar en cuenta cuanto producto descontar del inventario
# y calcular el total de la factura
class ProductoVenta(models.Model):
    producto = models.ForeignKey('Producto', on_delete=models.CASCADE)
    venta = models.ForeignKey('Venta', null=True, on_delete=models.SET_NULL)
    cantidad = models.DecimalField('Cantidad', decimal_places=2, max_digits=12, validators= [MinValueValidator(0)])

# Cliente de una venta
class Cliente(models.Model):
    dpi = models.BigIntegerField(
        unique=True,
        validators=[
            MaxValueValidator(9999999999999),

            MinValueValidator(100000000000)
        ],
        primary_key= True
    )
    nombre = models.CharField(max_length=200)
    nit = models.CharField(max_length=15)
    direccion = models.CharField(max_length=500)
    sedes = models.ManyToManyField('Sede', verbose_name='Sedes a las que pertenece el cliente')

    def __str__(self):
        return "%s [ %s ]" % (self.nombre, self.dpi)

# Factura de una venta, contiene el total de la venta junto si esta fue
# a domicilio se recarga 10% del subtotal
class Factura(models.Model):
    venta = models.ForeignKey('Venta', on_delete=models.SET_NULL, null=True)
    subtotal = models.DecimalField(decimal_places=2, max_digits=12)
    recargo = models.DecimalField(decimal_places=2, max_digits=5)
    total = models.DecimalField(decimal_places=2, max_digits=12)

# Estos logs sirven para revisar la actualizacion del inventario por parte
# del usuario encargado de sede
class LogActualizacionInventario(models.Model):
    producto = models.ForeignKey(
        'Producto', on_delete=models.SET_NULL, null=True)
    cantidad_nueva = models.IntegerField()
    cantidad_vieja = models.IntegerField()
    descripcion = models.CharField(max_length=500)
    usuario = models.ForeignKey(
        settings.AUTH_USER_MODEL, on_delete=models.SET_NULL, null=True)
    fecha = models.DateField('Fecha de cambio', auto_now_add=True)

frontend/sedes/templates/ventas/venta_confirm_delete.html
<!-- Esta vista muestra una confirmacion si se desea eliminar una sede -->

{% extends '../base.html' %}
{% block body_block %}

<h1>Eliminar &quot;{{ object.nombre }}&quot;</h1>
<form method="post">
    {% csrf_token %}
    <p>
        <strong>¿Estas seguro que deseas eliminar este cliente?</strong>
    </p>
    <br>
    <input class="btn btn-danger" type="submit" value="Confirmar" />
</form>

{% endblock %}

frontend/sedes/templates/ventas/venta_detail.html
<!-- Esta vista muestra el detalle de una sede -->

{% extends '../base.html' %}
{% block body_block %}

<h2>Detalles de la venta</h2>
<table class="table table-hover table-bordered">
    <tr>
      <th colspan="2">Venta #{{ object.id }}</th>
    </tr>
    <tr>
      <td>Cliente</td>
      <td><a href='{% url "lista_clientes" %}'>{{object.cliente}}</a>
        </td>
    </tr>
    <tr>
      <td>Vendedor</td>
      <td><a href='{% url "ver_usuario" object.vendedor.dpi %}'>{{object.vendedor}}</a></td>
    </tr>
    <tr>
      <td>Fecha Facturación</td>
      <td>{{ object.fecha_facturacion }}</td>
    </tr>
    <tr>
      <td>Tipo</td>
      <td>{% if object.tipo == 'D' %}A domicilio{% else %}En el local{% endif %}</td>
    </tr>
    {% if object.repartidor %}
    <tr>
      <td>Repartidor</td>
      <td><a href='{% url "ver_usuario" object.repartidor.dpi %}'>{{object.repartidor}}</a></td>
    </tr>
    {% endif %}
    <tr>
      <td>Fecha Entrega</td>
      <td>{{ object.fecha_entrega }}</td>
    </tr>
    <tr>
      <td>Estado de Entrega</td>
      <td>{% if object.entregada %} Entregada {% else %} Pendiente {% endif %}</td>
    </tr>
  </table>

<h2>Productos vendidos</h2>

<table class="table table-bordered table-hover table-stripped">
    <tr>
      <th>SKU</th>
      <th>NOMBRE</th>
      <th>PRECIO (Q)</th>
      <th>CANTIDAD (Unidades)</th>
      <th>SUBTOTAL (Q)</th>
      <th>TOTAL ACUMULADO (Q)</th>
    </tr>
    {% for pv in factura %}
    <tr>
      <td>{{ pv.producto.sku }}</td>
      <td>{{ pv.producto.nombre }}</td>
      <td>{{ pv.producto.precio }}</td>
      <td>{{ pv.cantidad }}</td>
      <td>{{ pv.subtotal }}</td>
      <td>{{ pv.total }}</td>
    </tr>
    {% endfor %}
    
    <tr>
        <td colspan="5">Total</td>
        <td>Q.{{ total }}</td>
    </tr>
  </table>

{% endblock %}

frontend/sedes/templates/ventas/venta_form.html
<!-- Esta vista muestra todas las sedes que hay disponibles -->

{% extends '../base.html' %}
{% block body_block %}

<h1>Crear una venta</h1>
<hr>

<div class="jumbotron">

    <form method="post" class="form" id="create_venta_form">
        {% csrf_token %}

        <p>
            <label for="id_cliente">Cliente:</label> <select name="cliente" class="form-control" required
                id="id_cliente">

                <option value="" selected>---------</option>

                {% for cliente in clientes %}

                <option value="{{cliente.dpi}}">{{cliente}}</option>

                {% endfor %}

            </select>
        </p>
        <p>
            <label for="id_fecha_facturacion">Fecha de facturacion:</label>

            <input type="date" name="fecha_facturacion" class="form-control" required id="id_fecha_facturacion"
                min="2000-01-01" max="2025-01-01">
        </p>

        <div class="row">
            <div class="col-md-12">
                <h2>Agregar productos</h2>
            </div>

            <div class="col-md-4">
                <h3>1. Seleccionar bodegas</h3>
                <label for="id_bodegas">Bodegas:</label>
                <select name="bodegas" class="form-control" id="id_bodegas" multiple style="height: 250px;">

                </select>
            </div>

            <div class="col-md-4">
                <h3>2. Seleccionar productos</h3>
                <label for="id_productos">Productos seleccionados:</label>
                <select name="productos" class="form-control" id="id_productos" multiple style="height: 250px;">

                </select>
            </div>
            <div class="col-md-4">
                <h3>3. Seleccionar cantidad</h3>
                <label for="producto_qtty">Cantidad de productos a agregar:</label>

                <input type="number" id="producto_qtty" step="1" min="1" value="1" class="form-control"
                    placeholder="Cantidad de productos...">
                <p></p>
                <input type="button" id="btn_add" onclick="agregar_producto()" value="aceptar"
                    class="btn btn-primary btn-block" />
            </div>

            <div class="col-md-12">
                <h3>Productos Agregados</h3>
                <hr>

                <label for="productos_agregados">Productos agregados:</label>
                <input type="button" id="btn_remove_product" onclick="remove_selected_products()"
                    value="Remover elementos seleccionados" class="btn btn-xs btn-danger pull-right" />
                <select name="productos_agregados" class="form-control" id="productos_agregados" multiple
                    style="height: 250px;">

                </select>
                <p></p>
            </div>
        </div>
        </p>
        <hr>
        <p>
            <label for="id_tipo">Tipo de entrega:</label>
            <select name="tipo" class="form-control" id="id_tipo">
                <option value="D">A domicilio</option>
                <option value="L" selected>Local</option>
            </select>
        </p>

        <p id="repartidor_container" hidden>
            <label for="id_repartidor">Repartidor:</label>
            <select name="repartidor" class="form-control" id="id_repartidor">
                <option value="" selected>---------</option>

                {% for repartidor in repartidores %}

                <option value="{{repartidor.email}}">{{repartidor}}</option>

                {% endfor %}

            </select></p>
        <p>

            <input class="btn btn-success" type="submit" value="Aceptar" />
    </form>

</div>


<script>

    let bodega_productos = JSON.parse(`{{bodega_productos|safe}}`);

    function buscar_bodega(index) {
        if (index < 0 || index >= bodega_productos.length) {
            return null;
        }

        return bodega_productos[index]
    }

    function buscar_producto_bodega(pindex) {

        for (let j = 0; j < bodega_productos.length; j++) {
            let bodega = bodega_productos[j]
            for (let i = 0; i < bodega.productos.length; i++) {
                let producto = bodega.productos[i];

                if (producto.index == pindex) {
                    return { bodega: bodega, producto: producto };
                }
            }
        }

        return null;
    }

    function buscar_producto(pindex) {
        let producto_bodega = buscar_producto_bodega(pindex);
        if (!producto_bodega) {
            return -1;
        }
        return producto_bodega.producto;
    }

    function mostrar_productos() {

        let bodegas = $("#id_bodegas").val();

        $('#id_productos option').remove();

        bodegas.forEach(bindex => {
            let bodega = buscar_bodega(bindex * 1);
            if (!bodega) {
                return;
            }
            $('#id_productos').append($('<option>', {
                value: "-1",
                text: `── Bodega "${bodega.nombre}" ──`,
                disabled: true,
                style: "font-weight: bold"
            }));

            $('#id_productos').append($('<option>', {
                value: "-1",
                text: ``,
                disabled: true,
                style: "font-weight: bold"
            }));

            bodega.productos.forEach(producto => {
                $('#id_productos').append($('<option>', {
                    value: producto.index,
                    text: `${producto.nombre} (${producto.cantidad} unidades en total)`,
                    disabled: producto.cantidad == 0,
                    style: producto.cantidad == 0 ? "color: red" : "color: blue"
                }));
            });


            $('#id_productos').append($('<option>', {
                value: "-1",
                text: ``,
                disabled: true,
                style: "font-weight: bold"
            }));
        })

    }

    bodega_productos.forEach((bodega, index) => {

        $('#id_bodegas').append($('<option>', {
            value: index,
            text: bodega.nombre + (bodega.activada ? "" : " (inactiva)"),
            selected: index == 0,
            disabled: !bodega.activada
        }));
    });

    mostrar_productos()

    function remove_selected_products() {
        $("#productos_agregados").val().forEach(v => {
            datos = v.split("#_v_#");

            let pid = datos[3] * 1
            let qtty = datos[1] * 1

            let producto = buscar_producto(pid);

            producto.cantidad += qtty;

            $(`#productos_agregados option[value='${v}']`).remove();
        });

        mostrar_productos();
    }

    function buscar_nombre_bodega(index) {
        let bodega = buscar_bodega(index);
        if (!bodega) {
            return "";
        }
        return bodega.nombre;
    }

    function agregar_producto() {

        let products_indexes = $("#id_productos").val();
        if (products_indexes <= 0) {
            alert("Por favor selecciona un producto");
            return;
        }

        let qtty = $("#producto_qtty").val();
        if (qtty <= 0) {
            alert("Por favor ingresa una cantidad valida");
            return;
        }

        products_indexes.forEach(pindex => {

            let producto_bodega = buscar_producto_bodega(pindex);
            if (!producto_bodega) {
                alert("Por favor selecciona un producto valido");
                return;
            }

            let producto = producto_bodega.producto
            if (!producto) {
                alert("Por favor selecciona un producto valido");
                return;
            }

            let bodega = producto_bodega.bodega
            if (!bodega) {
                alert("Por favor selecciona un producto de una bodega");
                return;
            }

            if (producto.cantidad < qtty) {
                alert("No hay en existencia " +
                    `${qtty} unidades del producto ` +
                    `"${producto.nombre}"" (${producto.cantidad} unidades disponibles) ` +
                    `en "${bodega.nombre}"`)

                return;
            }

            producto.cantidad = producto.cantidad - qtty;

            //let product_name = $(`#id_productos option[value='${product_id}']`).text();

            $('#productos_agregados').append($('<option>', {
                value: `${producto.id}#_v_#${qtty}#_v_#${bodega.id}#_v_#${producto.index}`,
                text: `${qtty} unidades de ${producto.nombre} - ${bodega.nombre}`,
                style: "color: green",
            }));

            mostrar_productos();
        });

    }

    function prepare_form() {
        let agregados = $("#productos_agregados option");

        if (agregados.length > 0) {
            $('#productos_agregados option').prop('selected', true);
            return true;
        }
        else {
            alert('Por favor agregar productos a la venta');
        }

        return false;
    }

    $('#create_venta_form').submit(function () {
        return prepare_form();
    });

    $('#id_bodegas').on('change', function () {
        let bodegas = $("#id_bodegas").val();
        bodegas.forEach(bodega => {
            mostrar_productos(bodega)
        });
    });

    $('#id_tipo').on('change', function () {
        $("#id_repartidor option[value='']").prop('selected', true);

        if (this.value == 'L') {
            $("#repartidor_container").prop('hidden', true);
            $("#id_repartidor").prop('required', false);
        }
        else if (this.value == 'D') {
            $("#repartidor_container").prop('hidden', false);
            $("#id_repartidor").prop('required', true);
        }
    });

    document.getElementById("id_fecha_facturacion").valueAsDate = new Date()

</script>

{% endblock %}

frontend/sedes/templates/ventas/venta_pdf.html
<table class="table table-hover table-bordered">
    <tr>
      <th colspan="2">Venta #{{ object.id }}</th>
    </tr>
    <tr>
      <td>Cliente</td>
      <td><a href='{% url "lista_clientes" %}'>{{object.cliente}}</a>
        </td>
    </tr>
    <tr>
      <td>Vendedor</td>
      <td><a href='{% url "ver_usuario" object.vendedor.dpi %}'>{{object.vendedor}}</a></td>
    </tr>
    <tr>
      <td>Fecha Facturación</td>
      <td>{{ object.fecha_facturacion }}</td>
    </tr>
    <tr>
      <td>Tipo</td>
      <td>{% if object.tipo == 'D' %}A domicilio{% else %}En el local{% endif %}</td>
    </tr>
    {% if object.repartidor %}
    <tr>
      <td>Repartidor</td>
      <td><a href='{% url "ver_usuario" object.repartidor.dpi %}'>{{object.repartidor}}</a></td>
    </tr>
    {% endif %}
    <tr>
      <td>Fecha Entrega</td>
      <td>{{ object.fecha_entrega }}</td>
    </tr>
    <tr>
      <td>Estado de Entrega</td>
      <td>{% if object.entregada %} Entregada {% else %} Pendiente {% endif %}</td>
    </tr>
  </table>

<h2>Productos vendidos</h2>

<table class="table table-bordered table-hover table-stripped">
    <tr>
      <th>SKU</th>
      <th>NOMBRE</th>
      <th>PRECIO (Q)</th>
      <th>CANTIDAD (Unidades)</th>
      <th>SUBTOTAL (Q)</th>
      <th>TOTAL ACUMULADO (Q)</th>
    </tr>
    {% for pv in factura %}
    <tr>
      <td>{{ pv.producto.sku }}</td>
      <td>{{ pv.producto.nombre }}</td>
      <td>Q {{ pv.producto.precio }}</td>
      <td>{{ pv.cantidad }} unidades</td>
      <td>Q {{ pv.subtotal }}</td>
      <td>Q {{ pv.total }}</td>
    </tr>
    {% endfor %}
    
    {% if object.tipo == 'D' %}
    <tr>
        <td colspan="4">Recargo por servicio a domicilio (10%)</td>
        <td>Q {{ total_10p }}</td>
        <td>Q {{ total_recargo }}</td>
      </tr>
      <tr>
          <td colspan="5">Total</td>
          <td>Q {{ total_recargo }}</td>
      </tr>
    {%else %}
    
    <tr>
        <td colspan="5">Total</td>
        <td>Q {{ total }}</td>
    </tr>
    {% endif %}
  </table>

frontend/sedes/templates/ventas/ventas_list.html
<!-- Esta vista muestra todas las sedes que hay disponibles -->

{% extends '../base.html' %}
{% block body_block %}

<h1>Ventas</h1>

<a class="btn btn-success" href="{% url "crear_venta" %}">Crear venta</a>

<table class="table table-striped">
    <thead class="thead-dark">
        <tr>
            <th>Cliente</th>
            <th>Vendedor</th>
            <th>Fecha de Facturacion</th>
            <th>Tipo de entrega</th>
            <th>Fecha de entrega</th>
            <th>Entregado</th>
            <th colspan="2">Acciones</th>
        </tr>
    </thead>
    <tbody class="table-hover">
        {% for venta in object_list %}
        <tr>
            <td>{{ venta.cliente }}</td>
            <td>{{ venta.vendedor }}</td>
            <td>{{ venta.fecha_facturacion }}</td>
            <td>{% if venta.tipo == 'L' %} <span class='text-success'>Local</span> {% else %} <span class='text-primary'>Domicilio</span> {% endif %}</td>
            <td>{{ venta.fecha_entrega }}</td>
            <td>{% if venta.entregada %} <span class='text-success'>Entregada</span> {% else %} <span class='text-danger'>Pendiente</span> {% endif %}</td>
            
            <td>
                <a href="{% url "detalle_venta"  venta.id  %}"> <span class="glyphicon glyphicon-eye-open">&nbsp;</span></a>
            </td>
        </tr>
        {% endfor %}
    </tbody>
</table>

{% endblock %}